# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
proc start_step { step } {
  set stopFile ".stop.rst"
  if {[file isfile .stop.rst]} {
    puts ""
    puts "*** Halting run - EA reset detected ***"
    puts ""
    puts ""
    return -code error
  }
  set beginFile ".$step.begin.rst"
  set platform "$::tcl_platform(platform)"
  set user "$::tcl_platform(user)"
  set pid [pid]
  set host ""
  if { [string equal $platform unix] } {
    if { [info exist ::env(HOSTNAME)] } {
      set host $::env(HOSTNAME)
    }
  } else {
    if { [info exist ::env(COMPUTERNAME)] } {
      set host $::env(COMPUTERNAME)
    }
  }
  set ch [open $beginFile w]
  puts $ch "<?xml version=\"1.0\"?>"
  puts $ch "<ProcessHandle Version=\"1\" Minor=\"0\">"
  puts $ch "    <Process Command=\".planAhead.\" Owner=\"$user\" Host=\"$host\" Pid=\"$pid\">"
  puts $ch "    </Process>"
  puts $ch "</ProcessHandle>"
  close $ch
}

proc end_step { step } {
  set endFile ".$step.end.rst"
  set ch [open $endFile w]
  close $ch
}

proc step_failed { step } {
  set endFile ".$step.error.rst"
  set ch [open $endFile w]
  close $ch
}

set_msg_config  -id {Constraints 18-5210}  -string {{WARNING: [Constraints 18-5210] No constraints selected for write.
Resolution: This message can indicate that there are no constraints for the design, or it can indicate that the used_in flags are set such that the constraints are ignored. This later case is used when running synth_design to not write synthesis constraints to the resulting checkpoint. Instead, project constraints are read when the synthesized design is opened.}}  -suppress 
set_msg_config  -id {Timing 38-282}  -string {{CRITICAL WARNING: [Timing 38-282] The design failed to meet the timing requirements. Please see the timing summary report for details on the timing violations.}}  -suppress 

start_step init_design
set ACTIVE_STEP init_design
set rc [catch {
  create_msg_db init_design.pb
  create_project -in_memory -part xc7z010clg400-1
  set_property design_mode GateLvl [current_fileset]
  set_param project.singleFileAddWarning.threshold 0
  set_property webtalk.parent_dir {C:/Users/david/Desktop/Rasla_Davide_505828/VHDL project JustOne/vivado/Vivado_With_One_Reg/Vivado_With_One_Reg.cache/wt} [current_project]
  set_property parent.project_path {C:/Users/david/Desktop/Rasla_Davide_505828/VHDL project JustOne/vivado/Vivado_With_One_Reg/Vivado_With_One_Reg.xpr} [current_project]
  set_property ip_output_repo {{C:/Users/david/Desktop/Rasla_Davide_505828/VHDL project JustOne/vivado/Vivado_With_One_Reg/Vivado_With_One_Reg.cache/ip}} [current_project]
  set_property ip_cache_permissions {read write} [current_project]
  add_files -quiet {{C:/Users/david/Desktop/Rasla_Davide_505828/VHDL project JustOne/vivado/Vivado_With_One_Reg/Vivado_With_One_Reg.runs/synth_1/ConvolutionalGenerator.dcp}}
  read_xdc {{C:/Users/david/Desktop/Rasla_Davide_505828/VHDL project JustOne/vivado/Vivado_With_One_Reg/Vivado_With_One_Reg.srcs/constrs_1/new/Timing_8.xdc}}
  link_design -top ConvolutionalGenerator -part xc7z010clg400-1
  close_msg_db -file init_design.pb
} RESULT]
if {$rc} {
  step_failed init_design
  return -code error $RESULT
} else {
  end_step init_design
  unset ACTIVE_STEP 
}

start_step opt_design
set ACTIVE_STEP opt_design
set rc [catch {
  create_msg_db opt_design.pb
  opt_design 
  write_checkpoint -force ConvolutionalGenerator_opt.dcp
  create_report "impl_1_opt_report_drc_0" "report_drc -file ConvolutionalGenerator_drc_opted.rpt -pb ConvolutionalGenerator_drc_opted.pb -rpx ConvolutionalGenerator_drc_opted.rpx"
  close_msg_db -file opt_design.pb
} RESULT]
if {$rc} {
  step_failed opt_design
  return -code error $RESULT
} else {
  end_step opt_design
  unset ACTIVE_STEP 
}

start_step place_design
set ACTIVE_STEP place_design
set rc [catch {
  create_msg_db place_design.pb
  if { [llength [get_debug_cores -quiet] ] > 0 }  { 
    implement_debug_core 
  } 
  place_design 
  write_checkpoint -force ConvolutionalGenerator_placed.dcp
  create_report "impl_1_place_report_io_0" "report_io -file ConvolutionalGenerator_io_placed.rpt"
  create_report "impl_1_place_report_utilization_0" "report_utilization -file ConvolutionalGenerator_utilization_placed.rpt -pb ConvolutionalGenerator_utilization_placed.pb"
  create_report "impl_1_place_report_control_sets_0" "report_control_sets -verbose -file ConvolutionalGenerator_control_sets_placed.rpt"
  close_msg_db -file place_design.pb
} RESULT]
if {$rc} {
  step_failed place_design
  return -code error $RESULT
} else {
  end_step place_design
  unset ACTIVE_STEP 
}

start_step route_design
set ACTIVE_STEP route_design
set rc [catch {
  create_msg_db route_design.pb
  route_design 
  write_checkpoint -force ConvolutionalGenerator_routed.dcp
  create_report "impl_1_route_report_drc_0" "report_drc -file ConvolutionalGenerator_drc_routed.rpt -pb ConvolutionalGenerator_drc_routed.pb -rpx ConvolutionalGenerator_drc_routed.rpx"
  create_report "impl_1_route_report_methodology_0" "report_methodology -file ConvolutionalGenerator_methodology_drc_routed.rpt -pb ConvolutionalGenerator_methodology_drc_routed.pb -rpx ConvolutionalGenerator_methodology_drc_routed.rpx"
  create_report "impl_1_route_report_power_0" "report_power -file ConvolutionalGenerator_power_routed.rpt -pb ConvolutionalGenerator_power_summary_routed.pb -rpx ConvolutionalGenerator_power_routed.rpx"
  create_report "impl_1_route_report_route_status_0" "report_route_status -file ConvolutionalGenerator_route_status.rpt -pb ConvolutionalGenerator_route_status.pb"
  create_report "impl_1_route_report_timing_summary_0" "report_timing_summary -max_paths 10 -file ConvolutionalGenerator_timing_summary_routed.rpt -pb ConvolutionalGenerator_timing_summary_routed.pb -rpx ConvolutionalGenerator_timing_summary_routed.rpx -warn_on_violation "
  create_report "impl_1_route_report_incremental_reuse_0" "report_incremental_reuse -file ConvolutionalGenerator_incremental_reuse_routed.rpt"
  create_report "impl_1_route_report_clock_utilization_0" "report_clock_utilization -file ConvolutionalGenerator_clock_utilization_routed.rpt"
  create_report "impl_1_route_report_bus_skew_0" "report_bus_skew -warn_on_violation -file ConvolutionalGenerator_bus_skew_routed.rpt -pb ConvolutionalGenerator_bus_skew_routed.pb -rpx ConvolutionalGenerator_bus_skew_routed.rpx"
  close_msg_db -file route_design.pb
} RESULT]
if {$rc} {
  write_checkpoint -force ConvolutionalGenerator_routed_error.dcp
  step_failed route_design
  return -code error $RESULT
} else {
  end_step route_design
  unset ACTIVE_STEP 
}

