set_property SRC_FILE_INFO {cfile:C:/Users/david/Desktop/Rasla_Davide_505828/VHDL_project_TwoShift/vivado/CodeGenerator2Shift.srcs/constrs_1/new/genCon.xdc rfile:../../../CodeGenerator2Shift.srcs/constrs_1/new/genCon.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L16 [get_ports clk]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R18 [get_ports reset]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15 [get_ports ak_inputGen]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N16 [get_ports ak_OutpuTgen]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N20 [get_ports ck_outGen]
