set_property SRC_FILE_INFO {cfile:{C:/Users/david/Desktop/Rasla_Davide_505828/VHDL project JustOne/vivado/Vivado_With_One_Reg/Vivado_With_One_Reg.srcs/constrs_1/new/Timing_8.xdc} rfile:../../../Vivado_With_One_Reg.srcs/constrs_1/new/Timing_8.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L16 [get_ports clk]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R18 [get_ports reset]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D18 [get_ports ck_outGen]
